'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const fetchApi = async () => {
    try {
      const res = await axios.get(
        "https://api-shop-lks2.onrender.com/api/users?limit=10&page=1&order=created%20asc"
      );
      console.log("Response:", res.data);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  useEffect(() => {
    fetchApi();
  }, []);

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant="contained" onClick={fetchApi}>
        Hello world update
      </Button>
    </>
  );
}
